### ISSUE TITLE
[Nougat] flyme config - errors

### ISSUE THREAD

**Issue by Lyuu17** [FlymeOS/build#17]
Line 227: file/directory doesn't exists

I used a full ota from LineageOS 14.1

![image](https://user-images.githubusercontent.com/14199521/34642733-641a9d3a-f318-11e7-879b-75965e692ef1.png)

**Comment by JDKCHINA** [comment]
This Makefile must you copy base's Makefile ,but you copy is same you vendor.You can down.

**Comment by Ankris** [comment]
ok, I give up, there's a LOT of issues with these scripts. I can't use an OTA with a system image, the vendor files doesn't extract all...

**Comment by Lyuu17** [comment]
ok it seems I need to run "adb root" before anything!
