### ISSUE TITLE
Support the use of block-based OTAs in newproject

### ISSUE THREAD

**Issue by rafifos** [FlymeOS/build#9]
Since nobody is using file-based OTA for ROMs anymore (I haven't seen one since KK days..), we should start supporting block-based OTAs in projects..

**Comment by hexiaoshuai** [comment]
Thank you for your advice, the addition of `--block` in the `ota_from_target_files` add script can make oat package based on incremental block, but if the user has the behavior of incremental mount or modify the system partition will fail even if the upgrade files that change is not reflected in the incremental upgrade, so we still don't use block based incremental update.
